version: "3.9"

services:
  postgres-compose:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./travel.sqlite:/app/travel.sqlite
      - ./.pgpass:/app/.pgpass
  nifi:
    container_name: nifi
    hostname: nifi
    build:
      context: .
      dockerfile: DockerfileNiFi
      target: nifi
    ports:
      - 8443:8443
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      SINGLE_USER_CREDENTIALS_USERNAME: "admin" 
      SINGLE_USER_CREDENTIALS_PASSWORD: "ILvhISLIkaTlBACLUfhesmtTg"
      TZ: "America/Bahia"
    volumes:
      - ./Nifi/drivers:/opt/nifi/nifi-current/jdbc:rw
      - ./Nifi/data:/opt/nifi/data:rw
      - ./Nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./Nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./Nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./Nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./Nifi/state:/opt/nifi/nifi-current/state
      - ./Nifi/logs:/opt/nifi/nifi-current/logs
    networks:
      - postgres-compose-network
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "25m"
    cpus: 2
    mem_limit: 2g
    memswap_limit: 2g
    shm_size: 256m
    restart: always
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diego.castro@cefet-rj.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin


networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
